coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 10%         # Allowable drop
        informational: false  # Fail the PR if below target
    patch:
      default:
        target: 70%
        threshold: 10%
        informational: false
ignore:
  - "shared/src/commonMain/kotlin/com/andrea/tmdbshowcase/presentation/ui/**"
  - "shared/src/commonMain/kotlin/com/andrea/tmdbshowcase/di/**"