name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Run Unit Tests for iOS target
        run: ./gradlew :shared:iosX64Test

      - name: Build & Run Unit Tests for Android target
        run: ./gradlew :shared:testDebugUnitTest
